taller-rails/config/routes.rb
Taller::Application.routes.draw do
  resources :twits

  resources :users

  resources :trends

  get "home/index"

  root :to => "Trends#index" 

end

taller-rails/app/models/trend.rb
class Trend < ActiveRecord::Base 
  attr_accessible :name, :query, :url  
  
  validates_presence_of :name, :query
  
  validates_uniqueness_of :name  
  
  has_many :twits  
  
end

taller-rails/app/models/twit.rb
class Twit < ActiveRecord::Base
  attr_accessible :id_twit, :text, :url, :url_text, :trend, :user  
  
  validates_presence_of :id_twit, :trend, :user
  
  validates_uniqueness_of :id_twit
  
  belongs_to :trend
  belongs_to :user  
end

taller-rails/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :description, :followers_count, :friends_count, :location, :name, :screen_name
  
  validates_uniqueness_of :name, :screen_name
  
  validates_presence_of :name, :screen_name
  
  has_many :twits
end

taller-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

taller-rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

taller-rails/app/controllers/trends_controller.rb
require './lib/tweets/utils.rb'

class TrendsController < ApplicationController
  include Utils 
  
  # GET /trends
  # GET /trends.json
  def index 
    @trends = Trend.find(:all, :order => "id desc", :limit => 10) #the last ten trends    
  end

  # GET /trends/1
  # GET /trends/1.json
  def show    
    @trend = Trend.find(params[:id])
    
    TwitsController.new.new_twit @trend    
      
    @twits  = Twit.find(:all, :conditions => { :trend_id => @trend.id}, :order => "id desc", :limit => 10) #twits of trends       
  
  end  
 
  # GET /trends/new
  # GET /trends/new.json
  def new 
    begin   
      hash_of_trends = get_trends 
      if hash_of_trends[0] != nil      
        hash_of_trends[0]['trends'].each do |t|
          trend       = Trend.new
          trend.name  = t['name']
          trend.query = t['query']
          trend.url   = t['url']                   
          trend.save
        end            
      end
    rescue Exception => e
      logger.error e.inspect
    end
    redirect_to :action => :index
  end
end

taller-rails/app/controllers/twits_controller.rb
require './lib/tweets/utils.rb'
require './lib/tweets/crawler.rb'

class TwitsController < ApplicationController
  include Utils
  include Crawler
  
  def new_twit trend
    begin
      twits = Twit.find(:all, :conditions => {:trend_id => trend.id})      
      if twits.nil? or twits.count < 10 #if not exist twit on data base or twits.count < 10
        hash_of_twits = get_twits_for_trend trend.query #call api
        if not hash_of_twits['results'].nil?            
          hash_of_twits['results'].each do |t|
            begin
              twit          = Twit.new              
              twit.id_twit  = t['id_str']
              twit.text     = t['text']
              twit.url      = get_url twit.text #get url from twit text
              twit.url_text = get_url_text twit.url #get title from url              
              twit.trend    = trend #save trend id
              twit.user     = UsersController.new.new_user twit.id_twit.to_i #save user id                        
              twit.save #new twit on data base
            rescue Exception => e
              logger.error e.inspect
            end
          end
        end
      else #looking twits without user
        twits = Twit.find_all_by_user_id(nil, :conditions => {:trend_id => trend.id})
        if not twits.nil?
          twits.each do |t|
            t.user = UsersController.new.new_user t.id_twit.to_i #call user controller
            t.save #update twit on data base
          end
        end        
      end
    rescue Exception => e
      logger.error e.inspect
    end
  end
end

taller-rails/app/controllers/users_controller.rb
require './lib/tweets/utils.rb'

class UsersController < ApplicationController
  include Utils
  
  def new_user id_twit
    begin      
      hash_of_user = get_twit_by_id id_twit
      if hash_of_user != nil
        hash_user_twit            = hash_of_user['user']    
        screen_name               = hash_user_twit['screen_name']
        hash_of_user_information  = get_user_information_by_screen_name screen_name
      end      
      if hash_of_user_information != nil
        user = User.find(:first, :conditions => {:screen_name => hash_of_user_information['screen_name']})
        if user.nil? #if not exist user on data base 
          user                  = User.new
          user.name             = hash_of_user_information['name']
          user.screen_name      = hash_of_user_information['screen_name']
          user.location         = hash_of_user_information['location']
          user.description      = hash_of_user_information['description']
          user.followers_count  = hash_of_user_information['followers_count']
          user.friends_count    = hash_of_user_information['friends_count']        
          user.save #new user on data base
        end
        user
      end
    rescue Exception => e
      logger.error e.inspect
    end 
  end  

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end
end

taller-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

taller-rails/app/helpers/home_helper.rb
module HomeHelper
end

taller-rails/app/helpers/trends_helper.rb
module TrendsHelper  
end

taller-rails/app/helpers/twits_helper.rb
module TwitsHelper
end

taller-rails/app/helpers/users_helper.rb
module UsersHelper
end

taller-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trending Topic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>

taller-rails/app/views/trends/index.html.erb
<h1>Trending Topics</h1>

<table>
	<tr>
    	<td><h3>The Last Ten Trends</h3></td>
    	<td></td>
		<td></td>
		<td></td>
		<td><%= link_to 'Get Last Trending Topic', new_trend_path %></td>
  	</tr>
</table>

<table>
	<% i = 1 %>
	<% @trends.each do |trend| %>
		<tr>
	    	<th><%= i %> -</th><td><%= link_to trend.name, trend %></td>    
	  	</tr>
	  	<% i += 1 %>
	<% end %>
</table>

taller-rails/app/views/trends/show.html.erb
<h1>Twits of <%= @trend.name %></h1>

<table>
	<% i = 1 %>
	<% @twits.each do |twit| %>
		<tr>						
	    	<th><%= i %> - </th><td><%= twit.text %></td>	  	
	  		<% if not twit.user.nil? %>
	  	</tr>	
	  	<tr>
	  		<th></th><td><b>Posted by: </b><%= link_to twit.user.screen_name, twit.user %></td>	  	
	  		<% end %>	  	
	  		<% if not twit.url.nil? %>
	  	</tr>
	  		<th></th><td><b>Url: </b><%= twit.url %><b> - Text: </b><%= twit.url_text %></td>
	  		<% end %>
	  	</tr>
	  	<% i += 1 %>	  	
	<% end %>
</table>

<%= link_to 'Back to Trending Topic', trends_path %>

taller-rails/app/views/users/show.html.erb
<h1>Information of the user <%= @user.screen_name %> </h1>

<table>
	<tr>
		<td><b>Name:</b></td><td><%= @user.name %></td>
	</tr>
	<tr>
		<td><b>Location:</b></td><td><%= @user.location %></td>
	</tr>
	<tr>
		<td><b>Description:</b></td><td><%= @user.description %></td>
	</tr>
	<tr>
		<td><b>Followers count:</b></td><td><%= @user.followers_count %><td>
	</tr>
	<tr>
		<td><b>Friends count:</b></td><td><%= @user.friends_count %></td>
	</tr>
	<tr></tr>
	<tr></tr>
	<tr></tr>
</table>

<%= link_to 'Back to Twits', :back %>